select * from COMMUNITY_INFO;

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'COMMUNITY_INFO_AI_TRG';

SELECT TEXT
FROM USER_SOURCE
WHERE NAME = 'COMMUNITY_INFO_AI_TRG'
AND TYPE = 'TRIGGER';
